# Default values for redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry-vpc.cn-chengdu.aliyuncs.com/buf/redis
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "7.0.11"

volumes:
- name: redis-data
  persistentVolumeClaim:
    claimName: longhorn-redis-pvc

volumeMounts:
- name: redis-data
  mountPath: /data

imagePullSecrets: []
nameOverride: "redis"
fullnameOverride: "redis"

service:
  type: ClusterIP
  port: 6379

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}