# Default values for redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


image:
  repository: registry-vpc.cn-chengdu.aliyuncs.com/buf/redis
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "7.0.11"

deployment:
  enabled: false

# deployment use
volumes: {}
# volumes:
# - name: redis-data
#   persistentVolumeClaim:
#     claimName: longhorn-redis-pvc

volumeMounts:
- name: redis-data
  mountPath: /data

imagePullSecrets: []
nameOverride: "redis"
fullnameOverride: "redis"

service:
  type: ClusterIP
  port: 6379

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65

nodeSelector: {}

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: agent
          operator: Exists

statefulset:
  enabled: true

volumeClaimTemplates:
- metadata:
    name: redis-data
  spec:
    accessModes:
    - ReadWriteMany
    storageClassName: longhorn
    resources:
      requests:
        storage: 399Mi